config/routes.rb
Rails.application.routes.draw do
  get 'abouts/index'
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
          get :followed, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get '/about', to: "abouts#index"

  root 'restaurants#top'

  resources :restaurants do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :restaurant_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :restaurant_params

  def create
    favorite = current_user.favorites.new(restaurant_id: @restaurant.id)
    favorite.save
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, restaurant_id: @restaurant.id).destroy
  end

  private
  def restaurant_params
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <p>いいね！：
    <% if current_user.already_favorited?(restaurant) %>
        <%= link_to restaurant_favorites_path(restaurant), method: :delete, remote: true do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: red;">
                <%= restaurant.favorites.count %>
            </i>
        <% end %>
    <% else %>
        <%= link_to restaurant_favorites_path(restaurant), method: :post, remote: true do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: #C0C0C0;">
                <%= restaurant.favorites.count %>
            </i>
        <% end %>
    <% end %>
    <% else %>
    <i class="fa fa-heart" aria-hidden="true">
            <%= restaurant.favorites.count %>
    </i>
  </p>
<% end %>

app/views/favorites/create.js.erb
//投稿一覧いいね差し替え
$("#index_favorite_<%= @restaurant.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant}) %>");
//投稿詳細いいね差し替え
$("#show_favorite_<%= @restaurant.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant}) %>");

app/views/favorites/destroy.js.erb
//投稿一覧いいね差し替え
$("#index_favorite_<%= @restaurant.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant}) %>");
//投稿詳細いいね差し替え
$("#show_favorite_<%= @restaurant.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { restaurant: @restaurant}) %>");