config/routes.rb
Rails.application.routes.draw do
  get 'abouts/index'
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
          get :followed, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get '/about', to: "abouts#index"

  root 'restaurants#top'

  resources :restaurants do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.post_comments.build(post_comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = PostComment.find(params[:id])
    @comment.destroy
    render :index
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment, :restaurant_id, :user_id)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with(model: [restaurant, post_comment], url: restaurant_post_comments_path(@restaurant) ) do |f| %>
    <%= f.text_area :comment, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-primary" %>
<% end %>

app/views/post_comments/_index.html.erb
<!-- コメント内容(3件) ------------------------------------------------------------------>
<%= post_comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% post_comments.first(3).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            <div class="comment-text">
                ユーザー名：<%= link_to "#{comment.user.name}", user_path(comment.user.id) %>　<%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"img-circle", size: "40x40" %>
                <div class="comment-entry">
                   <%= comment.comment %>
                    <% if comment.user == current_user %>
                        <%= link_to restaurant_post_comment_path(comment.restaurant_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                    <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                    </span>
                </div>
            </div>
        </div>
    </li>
  <% end %>
<% end %>
<!-- コメント内容(4件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% post_comments.offset(3).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-text">
                            ユーザー名：<%= link_to "#{comment.user.name}", user_path(comment.user.id) %>　<%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"img-circle", size: "40x40" %>
                            <div class="comment-entry">
                               <%= comment.comment %>
                                <% if comment.user == current_user %>
                                    <%= link_to restaurant_post_comment_path(comment.restaurant_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                                <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                                </span>
                            </div>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>

app/views/post_comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { post_comments: @comment.restaurant.post_comments }) %>")
$("textarea").val('')