config/routes.rb
Rails.application.routes.draw do
  get 'abouts/index'
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
          get :followed, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get '/about', to: "abouts#index"

  root 'restaurants#top'

  resources :restaurants do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  attachment :profile_image

  has_many :restaurants, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  #いいね機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_restaurants, through: :favorites, source: :restaurant
  # フォロー機能
  has_many :followed_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :follower_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #いいね済みかどうか
  def already_favorited?(restaurant)
    self.favorites.exists?(restaurant_id: restaurant.id)
  end

   #フォローしているかを確認するメソッド
  def following?(user)
    followed_relationships.find_by(followed_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    followed_relationships.create!(followed_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    followed_relationships.find_by(followed_id: user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user

  def show
    @restaurants = Restaurant.where(user_id: @user.id)
    @favorite_restaurants = @user.favorite_restaurants
    @hash = Gmaps4rails.build_markers(@restaurants + @favorite_restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "restaurants/infowindow", locals: {restaurant: restaurant})
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def followed
    #@userがフォローしているユーザー
    @users = @user.followed
    render 'show_follow'
  end

  def followers
    #@userをフォローしているユーザー
    @users = @user.followers
    render 'show_follower'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!-- フォローボタン -->
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン(マイページのユーザーがcurrent_userでなければ表示 -->
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
    <!-- フォロー済みの場合 -->
      <%= render "unfollow" %>
    <% else %>
    <!-- フォローしていない場合 -->
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン -->
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <h3>
        <mark>プロフィール編集</mark>
      </h3>
      <%= form_with model: @user, url: user_path(params[:id]), method: :put, local: true do |f| %>
      <div class="form-group">
        <%= attachment_image_tag @user, :profile_image, class:"img-squere", id: :img_prev, fallback: "no_image.jpg", size:"200x200" %><br>
      </div>
      <div class="form-group">
        <%= f.attachment_field :profile_image, id: :user_img %>
      </div>
      <script type="text/javascript">
        $(function() {
          function readURL(input) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
            $('#img_prev').attr('src', e.target.result);
            }
           reader.readAsDataURL(input.files[0]);
          }
         }
        $("#user_img").change(function(){
            readURL(this);
         });
        });
      </script>
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, placeholder: @user.name, class: "form-control offset-1 col-5" %><br>
      </div>
      <div class="form-group">
        <%= f.label :introduction, '自己紹介' %>
        <%= f.text_area :introduction, placeholder:" 例）100文字以内", class: "form-control offset-1 col-5" %><br>
      </div>

      <div class="action">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %>さんのページ</h2>

<div class="container">
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-8">

<div class="content">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="user-edits">
          <h4 class="sideby">登録情報</h4>
          <% if current_user %>
          <% if @user.id == current_user.id %>
            <%= link_to "編集", edit_user_path, class: "btn btn-primary" %>
          <% end %>
          <% end %>
          </div>
        </div>

        <div class="row">
          <!--<div class="col-md-1">
          </div>
        -->
          <div class="col-md-6">
            <table class="table">
              <tr>
                <th class="th-bypage"><div class="text-center">名前</div></th>
                <td><div class="text-center"><%= @user.name %></div></td>
              </tr>
              <tr>
                <th class="th-bypage">
                  <div class="text-center">投稿数</div>
                </th>
                <td><div class="text-center">
                  <i class="fa fa-cutlery" aria-hidden="true"></i><%= @user.restaurants.count %></div>
                </td>
              </tr>
              <tr>
                <th class="th-bypage">
                  <div class="text-center">いいねした数</div>
                </th>
                <td><div class="text-center">
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i><%= @user.favorites.count %></div>
                </td>
              </tr>
            </table>
          </div>
          <div class="col-md-3 offset-md-6">
            <%= attachment_image_tag @user, :profile_image, size: "140x140", fallback: "no_image.jpg", class:"img-circle" %>
          </div>
          <div class="row">
            <div class="panel panel-default text-center border-dark mt-3 col-md-10">
              <div class="panel-heading text-primary">
                自己紹介
              </div>
              <div class="panel-body">
               <!-- <p class="panel-text"><%= @user.introduction %></p> -->
               <%= @user.introduction %>
              </div>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-1">
          </div>
          <div class="col-md-6">
            <div class="user-edits">
              <div id ="follow">
                <%= link_to followed_user_path(@user.id) do %>
                <h4 class="sideby">
                  フォロー<%= @user.followed.count %>人
                </h4>
                <% end %>
                <br>
              </div>
              <div id="follower">
                <%= link_to followers_user_path(@user.id) do %>
                <h4 class="sideby">フォロワー<%= @user.followers.count %>人</h4>
                <% end %>
              </div>
              <div>
              <%= render "follow_form" %>
              </div><br>
            </div>
          </div>
        </div>
</div>
      </div>
  </div>
</div>

<h4><%= @user.name %>さんの投稿＆いいねした投稿がマップに表示されます</h4>

<div id="map">
</div>

<style>
#map{
  height: 400px;
}
</style>

<script>
//Map表示
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<article id ="index">
  <div class="container">
    <div class="row">
      <section class="restaurants col-md-12">
        <h2><%= @user.name %>さんの最近の投稿</h2>
        <div class="row">
          <% @restaurants.order(created_at: "DESC").each do |restaurant| %>
          <div class="content col-md-3">
            <p><%= attachment_image_tag restaurant, :restaurant_image, size: "170x170", class: "img-100 pull-left profile-thumb", fallback: "no_image.jpg" %></p>
            <p>店名：<%= restaurant.name %></p>
            <p>
              <% restaurant.tags.first(3).each do |tag| %>
                <span class="label label-primary"><%= tag.name %></span>
              <% end %>
            </p>
            <p>住所：<%= restaurant.address %></p>
            <p>投稿者：<%= link_to user_path(restaurant.user_id) do %>
              <%= restaurant.user.name %>
              <% end %>
                <%= attachment_image_tag restaurant.user, :profile_image, size: "40x40", fallback: "no_image.jpg", class:"img-circle" %>
            </p>
            <p><%= link_to restaurant_path(restaurant) do %>
              詳細を見る
              <% end %></p>
            </div>
            <% end %>
          </div>
      </section>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <section class="restaurants col-md-12">
        <h2><%= @user.name %>さんがいいねした投稿</h2>
        <div class="row">
          <% @user.favorite_restaurants.order(created_at: "DESC").each do |restaurant| %>
          <div class="content col-md-3">
            <p><%= attachment_image_tag restaurant, :restaurant_image, size: "170x170", class: "img-100 pull-left profile-thumb", fallback: "no_image.jpg" %></p>
            <p>店名：<%= restaurant.name %></p>
            <p>
              <% restaurant.tags.first(3).each do |tag| %>
                <span class="label label-primary"><%= tag.name %></span>
              <% end %>
            </p>
            <p>住所：<%= restaurant.address %></p>
            <p>投稿者：<%= link_to user_path(restaurant.user_id) do %>
              <%= restaurant.user.name %>
              <% end %>
                <%= attachment_image_tag restaurant.user, :profile_image, size: "40x40", fallback: "no_image.jpg", class:"img-circle" %>
            </p>
            <p><%= link_to restaurant_path(restaurant) do %>
              詳細を見る
              <% end %></p>
            </div>
            <% end %>
          </div>
      </section>
    </div>
  </div>
</article>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <!-- <div class="col-md-2"></div> -->
    <div class="col-md-12">
      <h2>フォロー一覧</h2>

      <table class="table">

        <tr>
         <th>ユーザー名</th>
         <th>自己紹介文</th>
         <th></th>
        </tr>

        <% @user.followed.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, size: "60x60", fallback: "no_image.jpg", class:"img-circle" %>
            <%= link_to user_path(user.id) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td>
            <%= user.introduction %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
            詳細
            <% end %>
          </td>

        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <div class="row">
    <!-- <div class="col-md-2"></div> -->
    <div class="col-md-12">
      <h2>フォロー一覧</h2>

      <table class="table">

        <tr>
         <th>ユーザー名</th>
         <th>自己紹介文</th>
         <th></th>
        </tr>

        <% @user.followers.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, size: "60x60", fallback: "no_image.jpg", class:"img-circle" %>
            <%= link_to user_path(user.id) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td>
            <%= user.introduction %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
            詳細
            <% end %>
          </td>

        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>