config/routes.rb
Rails.application.routes.draw do
  get 'abouts/index'
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
          get :followed, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  get '/about', to: "abouts#index"

  root 'restaurants#top'

  resources :restaurants do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
#住所からlatitude,longitudeカラムを自動作成
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
#latitude,longitudeから住所取得
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  attachment :restaurant_image
  belongs_to :user
  #コメント機能
  has_many :post_comments, dependent: :destroy
  #いいね機能
  has_many :favorites, dependent: :destroy
  #タグ
  has_many :tags, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :top]

  PER = 16

  def top
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result(distinct: true).page(params[:page]).per(PER)
    #現在地を取得
    if params[:latitude].nil? && params[:longitude].nil?
      @latitude = 34.6873153
      @longitude = 135.52620130000003
      @zoom = 11
    else
      @latitude = params[:latitude].to_f
      @longitude = params[:longitude].to_f
      @zoom = 15
    end

    #地図とマーカーをセット
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "restaurants/infowindow", locals: {restaurant: restaurant})
    end
  end

  def index
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result(distinct: true).page(params[:page]).per(PER)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = User.find_by(id: @restaurant.user_id)
    @comment = PostComment.new
    @comments =@restaurant.post_comments
    #mapにmarker設置
    @latitude = @restaurant.latitude
    @longitude = @restaurant.longitude
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "restaurants/infowindow", locals: {restaurant: restaurant})
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      tags = Vision.get_image_data(@restaurant.restaurant_image)
      tags.each do |tag|
        @restaurant.tags.create(name: tag)
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.user_id == current_user.id
      redirect_to restaurant_path(@restaurant.id)
    else
      @restaurant.destroy
      redirect_to restaurants_path
    end
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :restaurant_image, :description, :address, :place_search)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_getposition.html.erb
<button onclick="getPosition();" class="btn btn-success">現在地を取得</button>

<script>

    // 現在地取得処理
    function getPosition() {
      // 現在地を取得
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
            window.location.href = "/?latitude="+position.coords.latitude+"&longitude="+position.coords.longitude
        },
        // 取得失敗した場合
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }
  </script>

app/views/restaurants/_infowindow.html.erb
<ul>
  <li><h4><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h4></li>
  <li><%= attachment_image_tag restaurant, :restaurant_image, size: "90x90", fallback: "no_image.jpg" %></li>
  <li><%= link_to "GoogleMapで開く", "https://maps.google.co.jp/maps?q=loc:#{restaurant.latitude},#{restaurant.longitude}&iwloc=J",target: "_blank" %></li>
</ul>

app/views/restaurants/_map.html.erb
<div id="map">
</div>

<style>
#map{
  width: 100%;
  height: 400px;
}
</style>

<script>
//Map表示
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setCenter(new google.maps.LatLng( <%= @latitude %>, <%= @longitude %>)); //初期位置設定
    handler.getMap().setZoom(<%= @zoom %>); //拡大率設定
  });
  </script>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant, url: restaurant_path(params[:id]), method: :put,local: true do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-danger"><%= @restaurant.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="container">
  <div class= "row">
    <div class="col-md-2">
    </div>

    <div class="col-md-4">
    <h3>
      <mark>投稿店舗の編集</mark>
    </h3>
    <div class="form-group row">
      <%= attachment_image_tag @restaurant, :restaurant_image, class: "img-square",id: :img_prev, fallback: "no_image.jpg", size:"300x300" %><br>
  </div>

  <div class="form-group row">
    <%= f.attachment_field :restaurant_image, id: :restaurant_img %>
  </div>
   </div>

  <script type="text/javascript">
    $(function() {
      function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
        }
       reader.readAsDataURL(input.files[0]);
      }
     }
    $("#restaurant_img").change(function(){
        readURL(this);
     });
    });
  </script>
  <div class="col-md-1">
  </div>

  <div class="col-md-4">
    <div class="form-group row">
      <%= f.label :name, '店名' %>
      <%= f.text_field :name, placeholder: @restaurant.name, class: "form-control offset-1 col-5" %><br>
    </div>

    <div class="form-group row">
      <%= f.label :description, '説明' %>
      <%= f.text_area :description, placeholder: @restaurant.description, class: "form-control offset-1 col-5" %><br>
    </div>

    <div class="form-group row">
      <%= f.label :address, '住所' %>
      <%= f.text_field :address, placeholder: @restaurant.address, class: "form-control offset-1 col-4" %><br>
    </div>

    <div class="actions">
      <%= f.submit '変更を保存', class: "btn btn-success" %>
    </div>
    </div>
  </div>
  </div>
    </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <div clss="row">
    <div class="search text-right">
      <h4>(ユーザー名・店名・地名)で検索を行う</h4>
       <%= search_form_for @q do |f| %>
       <%= f.label :name, "ユーザー名 or 店名 or 地名" %>
       <%= f.search_field :name_or_user_name_or_address_cont %>
       <%= f.submit "検索", class: "btn btn-primary" %>
       <% end %>
    </div>
  </div>
</div>

<article id ="index">
  <div class="container">
    <div class="row">
      <section class="restaurants col-md-12">
        <h2>最近の投稿</h2>
        <div class="row">
          <% @restaurants.order(created_at: "DESC").each do |restaurant| %>
          <div class="content col-md-3">
            <p><%= attachment_image_tag restaurant, :restaurant_image, size: "170x170", class: "img-100 pull-left profile-thumb", fallback: "no_image.jpg" %></p>
            <p>店名：<%= restaurant.name %></p>
            <p>
              <% restaurant.tags.first(3).each do |tag| %>
                <span class="label label-primary"><%= tag.name %></span>
              <% end %>
            </p>
            <p>住所：<%= restaurant.address %></p>
            <p>投稿者：<%= link_to user_path(restaurant.user_id) do %>
              <%= restaurant.user.name %>
              <% end %>
                <%= attachment_image_tag restaurant.user, :profile_image, size: "40x40", fallback: "no_image.jpg", class:"img-circle" %>
              </p>
            <p><%= link_to restaurant_path(restaurant) do %>
              詳細を見る
              <% end %></p>
            </div>
            <% end %>
          </div>
          <div class="row">
            <%= paginate @restaurants %>
          </div>
        </section>
      </div>
    </div>

</article>

app/views/restaurants/new.html.erb
<h2>オススメ店舗の登録</h2>

<%= form_with model: @restaurant, local: true do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-danger"><%= @restaurant.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="container">
  <div class= "row">
    <div class="col-md-2">
    </div>

    <div class="col-md-4">
    <h3>
      <mark>新規登録</mark>
    </h3>
    <div class="form-group row">
      <%= attachment_image_tag @restaurant, :restaurant_image, class: "img-square",id: :img_prev, fallback: "no_image.jpg", size:"300x300" %><br>
  </div>

  <div class="form-group row">
    <%= f.attachment_field :restaurant_image, id: :restaurant_img %>
  </div>
   </div>

  <script type="text/javascript">
    $(function() {
      function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
        }
       reader.readAsDataURL(input.files[0]);
      }
     }
    $("#restaurant_img").change(function(){
        readURL(this);
     });
    });
  </script>

  <div class="col-md-1">
  </div>

  <div class="col-md-4">
    <div class="form-group row">
      <%= f.label :name, '店名' %>
      <%= f.text_field :name, class: "form-control offset-1 col-5" %><br>
    </div>

    <div class="form-group row">
      <%= f.label :description, '説明' %>
      <%= f.text_area :description, class: "form-control offset-1 col-5" %><br>
    </div>

    <div class="form-group row">
      <%= f.label :address, '住所' %>
      <%= f.text_field :address, class: "form-control offset-1 col-4" %><br>
    </div>

    <div class="actions">
      <%= f.submit '新規登録', class: "btn btn-success" %>
    </div>
    </div>
  </div>
  </div>
    </div>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
<article id ="detail">

  <h2><%= @restaurant.name %></h2>
    <% if current_user %>
      <% if @user.id == current_user.id %>
        <%= link_to "編集", edit_restaurant_path(@restaurant.id), class: "btn btn-primary" %>
        <%= link_to "投稿を削除", restaurant_path(@restaurant.id), method: :delete, data: { confirm: "一度削除すると元には戻せません。本当に削除してもいいですか？"}, class: "btn btn-danger" %>
      <% end %>
    <% end %>

  <div class="content">
    <div class="container">
    <div class="col-md-8">
    <p class="picture_content"><%= attachment_image_tag @restaurant, :restaurant_image, size: "600x600", fallback: "no_image.jpg" %></p>
  </div>
  </div>
    <p>
      <strong>タグ：</strong>
      <% @restaurant.tags.each do |tag| %>
        <span class="label label-primary"><%= tag.name %></span>
      <% end %>
    </p>

    <p>
      <strong>説明文：</strong>
      <%= @restaurant.description %>
    </p>

    <p>
      <strong>投稿者：</strong>
      <%= link_to user_path(@user) do %>
      <%= @user.name %>
      <% end %>
      <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg", class:"img-circle" %>
    </p>

    <!-- いいね機能 -->
    <div id="show_favorite_<%= @restaurant.id %>">
      <%= render 'favorites/favorite', restaurant: @restaurant %>
    </div>

    <p>
      <strong>住所：</strong>
      <%= @restaurant.address %>
    </p>

    <div id="map">
    </div>

    <style>
    #map{
      width: 100%;
      height: 400px;
    }
    </style>

    <script>
    //Map表示
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setCenter(new google.maps.LatLng(<%= @latitude %>, <%= @longitude %>)); //初期位置設定
        handler.getMap().setZoom(15); //拡大率設定
      });
    </script>

    <!-- コメント機能 -->
    <p><strong>コメント：</strong></p>
    <div id="comments_area">
      <div class="">
          <ul>
            <li id="comments_area">
              <%= render partial: 'post_comments/index', locals: { post_comments: @comments } %>
            </li>
          </ul>
          <hr>
          <% if user_signed_in? %>
              <div class="comment-create">
                  <h5 class="text-left">コメントを投稿する</h5>
                  <%= render partial: 'post_comments/form', locals: { post_comment: @comment, restaurant: @restaurant } %>
              </div>
          <% end %>
      </div>
    </div>
  </div>
</article>
</div>

app/views/restaurants/top.html.erb
<h2>トップページ</h2>

<%= render "map" %>

<div class="container">
  <div clss="row">
     <div class="search">
      <h4>(ユーザー名・店名・地名)で検索を行う</h4>
       <%= search_form_for @q, url: root_path do |f| %>
       <%= f.search_field :name_or_user_name_or_address_cont %>
       <%= f.submit "検索", class: "btn btn-primary" %>
       <% end %>
       <p><strong>or</strong></p>
    </div>
    <div class="getposition">
      <h4>現在地から探す</h4>
      <%= render "getposition" %>
    </div>
  </div>
</div>

<article id ="index">
  <div class="container">
    <div class="row">
      <section class="restaurants col-md-12">
        <h2>最近の投稿</h2>
        <div class="row">
          <% @restaurants.order(created_at: "DESC").first(8).each do |restaurant| %>
          <div class="content col-md-3">
            <p><%= attachment_image_tag restaurant, :restaurant_image, size: "170x170", class: "img-100 pull-left profile-thumb", fallback: "no_image.jpg" %></p>
            <p>店名：<%= restaurant.name %></p>
            <p>
              <% restaurant.tags.first(3).each do |tag| %>
                <span class="label label-primary"><%= tag.name %></span>
              <% end %>
            </p>
            <p>住所：<%= restaurant.address %></p>
            <p>投稿者：<%= link_to user_path(restaurant.user_id) do %>
              <%= restaurant.user.name %>
              <% end %>
                <%= attachment_image_tag restaurant.user, :profile_image, size: "40x40", fallback: "no_image.jpg", class:"img-circle" %>
              </p>
            <p><%= link_to restaurant_path(restaurant) do %>
              詳細を見る
              <% end %></p>
            </div>
            <% end %>
          </div>
        </section>
      </div>
    </div>
</article>